### ISSUE TITLE
Non negative matrix factorization.

### ISSUE THREAD

**Issue by markroxor** [jellAIfish/jellyfish#39]
Consider a matrix V of 10000 rows and 500 columns, where each row represent words and each column represent documents. If we manage to factorize this matrix into two matrices of smaller dimensions, say W and H then the operations incurred to perform text processing on the two smaller matrices is very less compared to the larger matrix V.

Related paper - https://arxiv.org/pdf/1401.5226.pdf

**Comment by markroxor** [comment]
- [ ] Gensim is currently not using NNMF/NMF for reducing its computations. Send a PR?

**Comment by dikshant2210** [comment]
Is it same as non negative sampling in word2vec

**Comment by markroxor** [comment]
No.
Visit [this for details.](https://en.wikipedia.org/wiki/Non-negative_matrix_factorization)

**Comment by markroxor** [comment]
@dikshant2210  are you talking about negative sampling or non negative sampling?

**Comment by markroxor** [comment]
![screenshot from 2018-01-02 13-45-55](https://user-images.githubusercontent.com/11366315/34477884-6671ac48-efc3-11e7-8b36-d7e3f0cec9ad.png)

**Comment by markroxor** [comment]
The (i, j)th entry of the matrix X could for example be equal to the number of times the ith word appears in the jth document in which case each column of X is the vector of word counts of a document; in practice, more sophisticated constructions are used, e.g., the term frequency - inverse document frequency (tf-idf). This

**Comment by markroxor** [comment]
Algorithms for Non-negative Matrix Factorization
https://papers.nips.cc/paper/1861-algorithms-for-non-negative-matrix-factorization.pdf
